web/exmr/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.views.generic import TemplateView

from apps.accounts import views
from apps.accounts.forms import CustomPasswordResetForm
from apps.accounts.views import FeedbackListView

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.DashboardView.as_view(), name='profile'),
    path('address/', views.AddressView.as_view(), name='address'),
    path('add-new-address-complete/', views.AddAddressCompleteView.as_view(), name='add_new_address_complete'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('settings/', views.AccountSettings.as_view(), name='settings'),
    path('save-public-info/', views.PublicInfoSave.as_view(), name='save_public_info'),
    path('save-security-info/', views.SecurityInfoSave.as_view(), name='save_security_info'),
    path('save-ipn-settings/', views.IPNSettingsSave.as_view(), name='save_ipn_settings'),
    path('sign-up/', views.SignUpView.as_view(), name='signup'),
    path('ref-signup/<slug:mid>/', views.SignUpView.as_view(), name='signup'),
    path('sign-up-complete/', views.SignUpCompleteView.as_view(), name='signup_complete'),
    path('activate/<slug:key>', views.ProfileActivationView.as_view(), name='registration_activate'),
    path('password-reset/', PasswordResetView.as_view(template_name='accounts/forgot_password.html',
                                                     form_class=CustomPasswordResetForm), name='reset_password'),

    path('2fa-accounts/', views.TwoFactorAccountView.as_view(), name='accounts_2fa'),
    # path('2fa-list/', views.TwoFactorAccountList.as_view(), name='2fa_list'),
    path('delete-2fa/<int:pk>/', views.DeleteTwoFactorAccount.as_view(), name='delete_2fa'),
    path('delete-address/<int:pk>/', views.DeleteAddress.as_view(), name='delete_address'),
    path('verify-2fa/', views.Verify2FAView.as_view(), name='verify_2fa'),
    path('feedback/<slug:slug>/', FeedbackListView.as_view(), name='feedback'),
    path('feedback/', FeedbackListView.as_view(), name='feedbac'),
    path('verify-login/', views.VerifyLoginView.as_view(), name='verify_login'),
    path('login-notice/', views.LoginNoticeView.as_view(), name='login_notice'),
    path('kyc/', views.KYCView.as_view(), name='kyc'),
    path('kyc-accept/', views.KYCAcceptanceView.as_view(), name="kyc_accept"),
    path('view-profile-paybyname/', views.PayByNameCheck.as_view(), name="paybyname_check"),
]

web/exmr/apps/coins/urls.py
from django.urls import path
from django.views.generic import TemplateView

from apps.coins import views as coin_views
from apps.accounts.forms import CustomPasswordResetForm

app_name = 'coins'

urlpatterns = [
    path('wallets/', coin_views.WalletsView.as_view(), name='wallets'),
    path('supported/<str:type>/', coin_views.SupportedCoinView.as_view(),
         name='supported_coins'),
    path('newaddr/<str:currency>/', coin_views.NewCoinAddr.as_view(), name='newaddr'),
    path('<str:currency>/address/<int:pk>/update/', coin_views.CoinAddrUpdate.as_view(), name='label'),
    path('hidden_addr/<str:currency>/', coin_views.HiddenAddress.as_view(), name='hidden_addr'),
    path('newaddr/<str:currency>/hide/<int:pk>/', coin_views.CoinHide.as_view(), name='hide'),
    path('coin-conversion/<str:from>/<str:to>/',
         coin_views.ConvertCoinsView.as_view(), name='coin_conversion'),
    path('coin-conversion-confirm/',
         coin_views.CoinConversionFinalView.as_view(), name='conversion_final'),
    path('checkout/', TemplateView.as_view(template_name='coins/coin-checkout.html')),
    path('add-coin/', coin_views.AddNewCoin.as_view(), name='add-coin'),
    path('coin-settings/',coin_views.CoinSettings.as_view(),name='coin-settings'),
    path('coin-settings/setup/',coin_views.SettingSetUp.as_view(),name='setting-setup'),
    path('coin-settings/omini/',coin_views.OMiniView.as_view(),name='omini-coin'),
    path('coin-settings/ripple/',coin_views.RippleView.as_view(),name='ripple'),
    path('coin-withdrawal/<str:code>/', coin_views.CoinWithdrawal.as_view(), name='coin-withdrawal'),
    path('send/<slug:slug>/', coin_views.SendView.as_view(), name='send'),
    path('send-success/', coin_views.SendSuccessView.as_view(), name='send-success'),
    path('sendconfirm/<slug:slug>/', coin_views.SendConfirmView.as_view(), name='sendconfirm'),
    path('vote-details/<str:currency>/', coin_views.VoteDetailsView.as_view(), name='vote-details'),
    path('refund-claim/<slug:slug>/', coin_views.RefundClaimView.as_view(), name='refund-claim'),
    path('add-public-coin/', coin_views.NewCoinAddView.as_view(), name='add-public-coin' ),
    path('paybyname/', coin_views.PayByNameView.as_view(), name='paybyname' ),
    path('paybyname-payment/<int:pk>/', coin_views.PayByNamePayView.as_view(), name='paybyname-payment' ),
    path('paybyname-payment-final/', coin_views.PayByNamePaymentView.as_view(), name='pbnfinal' ),
    path('copromotion-form/', coin_views.CopromotionView.as_view(), name="copromotion-form"),
    path('get_balance/', coin_views.BalanceView.as_view(), name="get_balance"),
    path('get_all_coin_balance/', coin_views.AdminBalanceView.as_view(), name="get_all_coin_balance"),
    path('coin-vote-winners/', coin_views.VoteWinners.as_view(), name="winners"),
    path('coin-convert/<str:currency>', coin_views.CoinConvertView.as_view(), name="convert_select"),
    path('coin-convert-confirmation/', coin_views.CoinConvertView2.as_view(), name="convert_select_confirm"),
    path('coin-convert-complete/', coin_views.CoinConvertView3.as_view(), name="convert_select_finish"),
    path('currency-convert/', coin_views.ConversionView.as_view(), name="currency_convert"),
    path('insufficient/', TemplateView.as_view(template_name='coins/no-money.html'), name="low-balance"),
    path('paypal-verify/', coin_views.PayPalVerifyView.as_view(), name="paypal_verify"),
    path('buy-coin/<str:currency>/',coin_views.BuyCryptoView.as_view(), name="buy_coin"),
    path('displaysupportedcoins/',coin_views.DisplaySupportedCoins.as_view(), name="displaysupportedcoins"),
    path('admin-wallet/', coin_views.AdminWallet.as_view(), name="admin_wallet"),
    path('admin-wallet-coins/', coin_views.AdminWalletCoin.as_view(), name="admin_wallet_coin"),
    path('admin-coins-wallet/<str:coin>/', coin_views.AdminCoinWalletView.as_view(), name="admin_coin_wallet"),
    path('user-wallet/<int:pk>/', coin_views.UserWallet.as_view(), name="user_wallet"),
    path('transaction-history/', coin_views.TransactionHistoryView.as_view(), name='transaction-history'),
    path('transaction-history/<str:type>/', coin_views.TransactionDetails.as_view(), name='transaction-history-details'),
    path('download-txn/', coin_views.DownloadTxnView.as_view(), name="download_txn"),
    path('paybyname-submit', coin_views.PayByNameSubmit.as_view(), name="paybyname_submit"),
    path('paybyname-options/<int:pk>/', coin_views.PayByNameOptions.as_view(), name="paybyname_options"),
    path('get_current_rate/', coin_views.GetCurrentRate.as_view(), name="getcurrentrate"),



]

web/exmr/apps/common/urls.py
from django.urls import path
from django.views.generic import TemplateView

from apps.common.views import CoinRequestView, HelpTemplateView, HelpView, Update,\
                              PluginDownloadView, StaticPageView, ApiView, ApiTemplateView, ModeChangeView

app_name = 'common'

urlpatterns = [
    path('coin-hosting/', CoinRequestView.as_view(),  name='coinhosting'),
    path('api/', ApiView.as_view(), name='api'),
    path('api/<slug:slug>/', ApiTemplateView.as_view(), name='apitopic'),
    path('help/', HelpView.as_view(), name='help'),
    path('help/<slug:slug>/', HelpTemplateView.as_view(), name='helptopic'),
    path('plugin-download/', PluginDownloadView.as_view(), name='plugin-download'),
    path('update/', Update.as_view(), name='update'),
    path('coming-soon/', TemplateView.as_view(template_name='common/beta.html'), name='beta'),
    path('docs/<slug>/', StaticPageView.as_view(), name='staticpage'),
    path('change_color/', ModeChangeView.as_view(), name='change_mode')
]

web/exmr/apps/merchant_tools/urls.py
from django.urls import path
from django.views.generic import TemplateView

from apps.merchant_tools.views import (ButtonMakerView, CryptoPaymment, PaymentFormSubmitView, MercDocs,
                                       URLMakerView, URLMakerInvoiceView, POSQRMakerView, POSQRPayView, POSQRCompletePaymentView,ButtonMakerPayView,
                                       HelpTemplateView, DonationButtonMakerView, SimpleButtonMakerView, ButtonMakerContinuePayment, ButtonMakerInvoice,
                                       CryptoPaymmentV2, DonationButtonMakerInvoice, CryptoPaymmentSimple, SimpleButtonMakerInvoice, MTest)
# GCPS_V2
from apps.merchant_tools.views import (POSCalcView,POSCalcCoinSelect, POSCALCPayView)

app_name = 'mtools'

urlpatterns = [
    path('buttonmaker/', ButtonMakerView.as_view(),  name='buttonmaker'),
    path('donationbuttonmaker/', DonationButtonMakerView.as_view(),  name='donationbuttonmaker'),
    path('simplebuttonmaker/', SimpleButtonMakerView.as_view(),  name='simplebuttonmaker'),
    path('urlmaker/', URLMakerView.as_view(),  name='urlmaker'),
    path('invoice/<token>/', URLMakerInvoiceView.as_view(),  name='urlmakerinvoice'),
    path('make-payment/', CryptoPaymment.as_view(),  name='cryptopay'), 
    path('payment-process-1/', PaymentFormSubmitView.as_view(),  name='payprocess'),
    path('merchant-tools-docs/', MercDocs.as_view(),  name='mercdocs'),
    path('help/<slug:slug>/', HelpTemplateView.as_view(), name='helptopic'),
    path('pos-calculator/', POSCalcView.as_view(),  name='poscalc'),
    path('pos-calculator-select/', POSCalcCoinSelect.as_view(),  name='poscalcpaysel'),
    path('pos-calculator-final/', POSCALCPayView.as_view(),  name='poscalcfinal'),
    path('pos-qr/', POSQRMakerView.as_view(),  name='posqrmaker'),
    path('pos-qr/<token>/', POSQRPayView.as_view(),  name='pospay'),
    path('POSQRCompletePayment/', POSQRCompletePaymentView.as_view(),  name='posqrpay'),
    path('update-btn-form/', ButtonMakerContinuePayment.as_view(),  name='updatebtnmaker'),
    path('button-payment/', CryptoPaymmentV2.as_view(),  name='cryptopayV2'),
    path('simple-button-payment/', CryptoPaymmentSimple.as_view(),  name='cryptopaysimple'),
    path('donation-button-invoice-generate/', DonationButtonMakerInvoice.as_view(),  name='donorbtnpay'),
    path('simple-button-invoice-generate/', SimpleButtonMakerInvoice.as_view(),  name='simplebtnpay'),
    path('button-invoice-generate/', ButtonMakerInvoice.as_view(),  name='btnpay'),
    path('button-invoice-generate/<token>/', ButtonMakerInvoice.as_view(),  name='btnpay2'),
    path('simple-invoice-generate/<token>/', SimpleButtonMakerInvoice.as_view(),  name='simplebtnpay2'),
    path('donation-button-invoice-generate/<token>/', DonationButtonMakerInvoice.as_view(),  name='donorbtnpay2'),
    path('button-invoice-payment/', ButtonMakerPayView.as_view(),  name='btnqrcode'),
    path('mtest/', MTest.as_view(),  name='mtest'),
]

web/exmr/exmr/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from apps.coins.views import PublicCoinVote
from django.conf.urls import handler404, handler500
from apps.common.views import HomeView, ContactView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('s9tjjy6e8w6paimpmoxa4sfa651n6j.html/', TemplateView.as_view(template_name='s9tjjy6e8w6paimpmoxa4sfa651n6j.html'), name="facebook html"),
    path("zohoverify/verifyforzoho.html", TemplateView.as_view(template_name="verifyforzoho.html"), name="zoho"),
    path('', HomeView.as_view(), name='home'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('password-reset-done', PasswordResetDoneView.as_view(template_name='accounts/forgot_password_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('', include('apps.accounts.urls')),
    path('coins/', include('apps.coins.urls')),
    path('store/', include('apps.store.urls')),
    path('common/', include('apps.common.urls')),
    path('merchant_tools/', include('apps.merchant_tools.urls'), name='merchant_tools'),
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(template_name="accounts/login.html"), name='signin'),
    path('sign-up/', TemplateView.as_view(template_name='accounts/signup.html'),
         name='signup'),
    path('merchant-tools/', TemplateView.as_view(template_name='common/merchant-tools.html'), name='merchant-tools'),
    path('public-coin-votes/', PublicCoinVote.as_view(), name='public coin vote'),
    path('forgot-password/', TemplateView.as_view(template_name='accounts/forgot-password.html'),
         name='forgot-password'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('select2/', include('django_select2.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/exmr/apps/merchant_tools/forms.py
from django import forms
from apps.coins.models import Coin
from apps.merchant_tools.models import ButtonMaker, CryptoPaymentRec, URLMaker, POSQRMaker, DonationButtonMaker, ButtonImage, SimpleButtonMaker
from django.utils.safestring import mark_safe
from django.core.validators import DecimalValidator, URLValidator, ValidationError
from django_select2.forms import Select2MultipleWidget
from django.forms import Select

class CustomChoiceField(forms.ModelChoiceField):
    
    def label_from_instance(self, obj):
        return mark_safe("<span> &emsp;&emsp;   %s</span><img class='img-responsive w100px floatr ' style='margin-left: 30px;' src='%s'/> <br>"% (str(obj.label), obj.btn_img.url))


class ButtonMakerForm(forms.ModelForm):
    btn_image = CustomChoiceField(widget=forms.RadioSelect, queryset=ButtonImage.objects.all(), empty_label=None)

    class Meta:
        model = ButtonMaker
        exclude = ['']
        labels = {
        "item_amount":"Price in USD $"
        }

    def __init__(self, *args, **kwargs):
        super(ButtonMakerForm, self).__init__(*args, **kwargs)
        if self.fields['merchant_id']:
            self.fields['merchant_id'].disabled = True
        # self.fields['btn_image']=forms.ModelChoiceField(queryset=ButtonImage.objects.all())

class SimpleButtonMakerForm(forms.ModelForm):
    btn_image = CustomChoiceField(widget=forms.RadioSelect, queryset=ButtonImage.objects.all(), empty_label=None)

    class Meta:
        model = SimpleButtonMaker
        exclude = ['']
        labels = {
        "item_amount":"Price in USD $"
        }

    def __init__(self, *args, **kwargs):
        super(SimpleButtonMakerForm, self).__init__(*args, **kwargs)
        if self.fields['merchant_id']:
            self.fields['merchant_id'].disabled = True
        # self.fields['btn_image']=forms.ModelChoiceField(queryset=ButtonImage.objects.all())        

class DonationButtonMakerForm(forms.ModelForm):
    btn_image = CustomChoiceField(widget=forms.RadioSelect, queryset=ButtonImage.objects.all(), empty_label=None)
    
    class Meta:
        model = DonationButtonMaker
        exclude = []
        labels = {
        "item_amount":"Price in USD $"
        }

    def __init__(self, *args, **kwargs):
        super(DonationButtonMakerForm, self).__init__(*args, **kwargs)
        if self.fields['merchant_id']:
            self.fields['merchant_id'].disabled = True

class CryptoPaymentForm(forms.Form):
    class Meta:
        model = CryptoPaymentRec
        exclude = ['']


class URLMakerForm(forms.ModelForm):
    class Meta:
        model = URLMaker
        exclude = ['unique_id', 'URL_link']
        labels = {
        "item_amount":"Price in USD $"
        }

    def __init__(self, *args, **kwargs):
        super(URLMakerForm, self).__init__(*args, **kwargs)
        self.fields['merchant_id'].disabled = True


class POSQRForm(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        super (POSQRForm,self ).__init__(*args,**kwargs) # populates the post
        self.fields['currency'].queryset = Coins.objects.all()
        
    class Meta:
        model = POSQRMaker
        exclude=['URL_link','time_limit']

    def __init__(self, *args, **kwargs):
        super(POSQRForm, self).__init__(*args, **kwargs)
        self.fields['merchant_id'].disabled=True
        self.fields['unique_id'].disabled=True

web/exmr/templates/gcps/merchant_tools/pos_calc.html
{% extends 'gcps/testbase.html' %} {% load staticfiles widget_tweaks i18n %}{% load i18n %}
 <!-- body -->
 {% block content %}
 
    <section class="section section-pad" style="padding-bottom: 1em">
        <div class="container">
            <div class="bx-ash mb-2">
                <div class="grid-2-bx" style="display: inline">
                    <ul class="row nav nav-pills nav-fill " >
                        <li class="col-md-4 col-xs-6 col-lg-2 col-sm-6 col-xl-2 nav-item justify-content-center" >
                            <a href="{% url 'accounts:profile' %}" class="v-mid dashboard-nav" >
                                
                                <span class="dashboard-span hidden-xs hidden-sm wallet-menu"><i class="fas fa-tachometer-alt fa-2x  mr-4"></i>{% trans '&nbsp;&nbsp;&nbsp;Home' %}</span>
                            </a>
                            <!-- <i class="fas fa-2x fa-wallet"></i>
                            <a class="nav-link" href="{% url 'accounts:profile' %}"></a> -->
                        </li>
                        <li class="col-md-4 col-12 col-lg-2 col-sm-6 col-xl-2 nav-item justify-content-center">
                                <a href="{% url 'coins:wallets' %}" class="v-mid dashboard-nav ">
                                    
                                    <span class="dashboard-span hidden-xs hidden-sm wallet-menu">
                                        <i class="fas fa-2x fa-wallet mr-1"></i>{% trans 'Your Wallet' %}
                                    </span>
                                </a>
                            <!-- <a class="nav-link" href="{% url 'coins:wallets' %}">{% trans 'Your Wallet' %}</a> -->
                        </li>
                        <li class=" col-md-4 col-12 col-lg-2 col-sm-6 col-xl-2 nav-item justify-content-center">
                                <a href="{% url 'coins:coin-settings' %}" class="v-mid dashboard-nav">
                                    
                                    <span class="dashboard-span hidden-xs hidden-sm wallet-menu"><i class="fas fa-coins  fa-2x mr-1"></i>{% trans 'Coin Settings' %}</span>
                                </a>
                            <!-- <a class="nav-link" href="{% url 'coins:coin-settings' %}">{% trans 'Coin Settings' %}</a> -->
                        </li>
                        <li class=" col-md-4 col-12 col-lg-2 col-sm-6 col-xl-2 nav-item justify-content-center">
                            <a href="{% url 'coins:transaction-history' %}" class="v-mid dashboard-nav">
                                    
                                    <span class="dashboard-span hidden-xs hidden-sm wallet-menu"><i class="fas fa-receipt  fa-2x mr-1"></i> {% trans 'Transactions' %}</span>
                            </a>
                            <!-- <a class="nav-link" href="{% url 'coins:transaction-history' %}">{% trans 'Transactions' %}</a> -->
                        </li>
                        <li class="col-md-4 col-12 col-lg-2 col-sm-6 col-xl-2 nav-item justify-content-center">
                                <a href="{% url 'mtools:poscalc' %}" class="v-mid dashboard-nav">
                                    
                                    <span class="dashboard-span hidden-xs hidden-sm wallet-menu"><i class="fas fa-shopping-cart  fa-2x mr-1"></i> {% trans 'Quick POS' %}</span>
                                </a>
                            <!-- <a class="nav-link" href="{% url 'mtools:poscalc' %}"> {% trans 'Quick POS' %}</a> -->
                        </li>
                        <li class="col-md-4 col-12 col-lg-2 col-sm-6 col-xl-2 nav-item justify-content-center">
                                <a href="{% url 'coins:paybyname' %}" class="v-mid dashboard-nav ">
                                    
                                    <span class="dashboard-span hidden-xs hidden-sm wallet-menu"><i class="fas fa-user-tie  fa-2x mr-1"></i>{% trans 'PayByName' %}</span>
                                </a>
                            <!-- <a class="nav-link" href="{% url 'coins:paybyname' %}"> {% trans 'PayByName' %}</a> -->
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>   
 <section class="section section-pad" style="padding-top: 1em">
    <div class="col-12 col-md-12 offset-md-3 col-lg-4 offset-lg-4 py-5">
       <form id="coform" role="form"  action="{% url 'mtools:poscalcpaysel'%}" method="POST" class="container">
          {% csrf_token %} 
          <div class="container" >
             <div class="calc-border row d-flex mb-1 calc-bg">
                <!-- <h5 class="text-white col-md-8" style="margin-top: 31px;">Enter your order total:</h5> -->
                <input id="amountf" name="amountf" value="0" size="14" placeholder="Enter your order total: " class="calc-input col-sm-8 rounded-tl"> 
                <select class="btn btnpad calc-select rounded-tr col-md-4" value="" name="select_currency">
                   <option selected>USD</option>
                   {% for k,v in rates.items %}
                   <option value="{{k}}">{{k}} - {{v|floatformat:4}}</option>
                   {% endfor %}
                </select>
             </div>
             <div class="row calc-main-border">
                <div class="col-md-6 calc-padding"><button class="calc-border btn btnpad2 col-12 p-02 col-12" onClick="padClear(); return false;">CLEAR</button></div>
                <div class="col-md-6 calc-padding"><button class="calc-border btn btnpad3 col-12 p-03 col-12" onClick="padBack(); return false;">
                   <span class="fa fa-arrow-left"></span></button>
                </div>
                <div class="col-md-12 calc-padding d-flex">
                   <div class="col-md-4 calc-padding"><button class="calc-border btn btn-primary btnpad col-12 p-0" onClick="padPress(1); return false;">1</button></div>
                   <div class="col-md-4 calc-padding"><button class="calc-border btn btn-primary btnpad col-12 p-0" onClick="padPress(2); return false;">2</button></div>
                   <div class="col-md-4 calc-padding"><button class="calc-border btn btn-primary btnpad col-12 p-0" onClick="padPress(3); return false;">3</button></div>
                </div>
                <div class="col-md-12 calc-padding d-flex">
                   <div class="col-md-4 calc-padding"><button class="calc-border btn btn-primary btnpad col-12 p-0" onClick="padPress(4); return false;">4</button></div>
                   <div class="col-md-4 calc-padding"><button class="calc-border btn btn-primary btnpad col-12 p-0" onClick="padPress(5); return false;">5</button></div>
                   <div class="col-md-4 calc-padding"><button class="calc-border btn btn-primary btnpad col-12 p-0" onClick="padPress(6); return false;">6</button></div>
                </div>
                <div class="col-md-12 calc-padding d-flex">
                   <div class="col-md-4 calc-padding"><button class="calc-border btn btn-primary btnpad col-12 p-0" onClick="padPress(7); return false;">7</button></div>
                   <div class="col-md-4 calc-padding"><button class="calc-border btn btn-primary btnpad col-12 p-0" onClick="padPress(8); return false;">8</button></div>
                   <div class="col-md-4 calc-padding"><button class="calc-border btn btn-primary btnpad col-12 p-0" onClick="padPress(9); return false;">9</button></div>
                </div>
                <div class="col-md-12 calc-padding d-flex">
                   <div class="col-md-4 calc-padding"><button class="calc-border btn btn-primary btnpad col-12 p-0" onClick="padPress(0); padPress(0); return false;">00</button></div>
                   <div class="col-md-4 calc-padding"><button class="calc-border btn btn-primary btnpad col-12 p-0" onClick="padPress(0); return false;">0</button></div>
                   <div class="col-md-4 calc-padding"><button class="calc-border btn btn-primary btnpad col-12 p-0" onClick="padPeriod(); return false;">.</button></div>
                </div>
                <div class="col-md-6 calc-padding"><a href="{% url 'merchant-tools' %}"class="calc-border btn btnpad2 col-12 p-02 col-12 pad-calc"><span class="glyphicon glyphicon-arrow-left"></span>Back</a></div>
                <div class="col-md-6 calc-padding"><button class="calc-border btn btnpad3 col-12 p-03 col-12">Continue </button></div>
             </div>
          </div>
       </form>
    </div>
  </div>
 </section>
 {% endblock content %}
 {% block script %}
 <script type="text/javascript">
    var padel = null;
    function padSetup() {
     if (padel == null) {
         padel = document.getElementById('amountf');
     }
     return (padel != null) ? true:false;
    }
    function padClear() {
     if (padSetup()) {
         padel.value = '';
     }
    }
    function padPeriod() {
     if (padSetup()) {
         if (padel.value.indexOf('.') == -1) {
             padel.value = padel.value+'.';
         }
     }
    }
    function padBack() {
     if (padSetup()) {
         if (padel.value.length > 0) {
             padel.value = padel.value.slice(0, -1);
         }
     }
    }
    function padPress(i) {
     if (padSetup()) {
         padel.value = padel.value+i.toString();
     }
    }
 </script>
 {% endblock script %}