web/exmr/apps/coins/urls.py
from django.urls import path
from django.views.generic import TemplateView

from apps.coins import views as coin_views
from apps.accounts.forms import CustomPasswordResetForm

app_name = 'coins'

urlpatterns = [
    path('wallets/', coin_views.WalletsView.as_view(), name='wallets'),
    path('supported/<str:type>/', coin_views.SupportedCoinView.as_view(),
         name='supported_coins'),
    path('newaddr/<str:currency>/', coin_views.NewCoinAddr.as_view(), name='newaddr'),
    path('<str:currency>/address/<int:pk>/update/', coin_views.CoinAddrUpdate.as_view(), name='label'),
    path('hidden_addr/<str:currency>/', coin_views.HiddenAddress.as_view(), name='hidden_addr'),
    path('newaddr/<str:currency>/hide/<int:pk>/', coin_views.CoinHide.as_view(), name='hide'),
    path('coin-conversion/<str:from>/<str:to>/',
         coin_views.ConvertCoinsView.as_view(), name='coin_conversion'),
    path('coin-conversion-confirm/',
         coin_views.CoinConversionFinalView.as_view(), name='conversion_final'),
    path('checkout/', TemplateView.as_view(template_name='coins/coin-checkout.html')),
    path('add-coin/', coin_views.AddNewCoin.as_view(), name='add-coin'),
    path('coin-settings/',coin_views.CoinSettings.as_view(),name='coin-settings'),
    path('coin-settings/setup/',coin_views.SettingSetUp.as_view(),name='setting-setup'),
    path('coin-settings/omini/',coin_views.OMiniView.as_view(),name='omini-coin'),
    path('coin-settings/ripple/',coin_views.RippleView.as_view(),name='ripple'),
    path('coin-withdrawal/<str:code>/', coin_views.CoinWithdrawal.as_view(), name='coin-withdrawal'),
    path('send/<slug:slug>/', coin_views.SendView.as_view(), name='send'),
    path('send-success/', coin_views.SendSuccessView.as_view(), name='send-success'),
    path('sendconfirm/<slug:slug>/', coin_views.SendConfirmView.as_view(), name='sendconfirm'),
    path('vote-details/<str:currency>/', coin_views.VoteDetailsView.as_view(), name='vote-details'),
    path('refund-claim/<slug:slug>/', coin_views.RefundClaimView.as_view(), name='refund-claim'),
    path('add-public-coin/', coin_views.NewCoinAddView.as_view(), name='add-public-coin' ),
    path('paybyname/', coin_views.PayByNameView.as_view(), name='paybyname' ),
    path('paybyname-payment/<int:pk>/', coin_views.PayByNamePayView.as_view(), name='paybyname-payment' ),
    path('paybyname-payment-final/', coin_views.PayByNamePaymentView.as_view(), name='pbnfinal' ),
    path('copromotion-form/', coin_views.CopromotionView.as_view(), name="copromotion-form"),
    path('get_balance/', coin_views.BalanceView.as_view(), name="get_balance"),
    path('get_all_coin_balance/', coin_views.AdminBalanceView.as_view(), name="get_all_coin_balance"),
    path('coin-vote-winners/', coin_views.VoteWinners.as_view(), name="winners"),
    path('coin-convert/<str:currency>', coin_views.CoinConvertView.as_view(), name="convert_select"),
    path('coin-convert-confirmation/', coin_views.CoinConvertView2.as_view(), name="convert_select_confirm"),
    path('coin-convert-complete/', coin_views.CoinConvertView3.as_view(), name="convert_select_finish"),
    path('currency-convert/', coin_views.ConversionView.as_view(), name="currency_convert"),
    path('insufficient/', TemplateView.as_view(template_name='coins/no-money.html'), name="low-balance"),
    path('paypal-verify/', coin_views.PayPalVerifyView.as_view(), name="paypal_verify"),
    path('buy-coin/<str:currency>/',coin_views.BuyCryptoView.as_view(), name="buy_coin"),
    path('displaysupportedcoins/',coin_views.DisplaySupportedCoins.as_view(), name="displaysupportedcoins"),
    path('admin-wallet/', coin_views.AdminWallet.as_view(), name="admin_wallet"),
    path('admin-wallet-coins/', coin_views.AdminWalletCoin.as_view(), name="admin_wallet_coin"),
    path('admin-coins-wallet/<str:coin>/', coin_views.AdminCoinWalletView.as_view(), name="admin_coin_wallet"),
    path('user-wallet/<int:pk>/', coin_views.UserWallet.as_view(), name="user_wallet"),
    path('transaction-history/', coin_views.TransactionHistoryView.as_view(), name='transaction-history'),
    path('transaction-history/<str:type>/', coin_views.TransactionDetails.as_view(), name='transaction-history-details'),
    path('download-txn/', coin_views.DownloadTxnView.as_view(), name="download_txn"),
    path('paybyname-submit', coin_views.PayByNameSubmit.as_view(), name="paybyname_submit"),
    path('paybyname-options/<int:pk>/', coin_views.PayByNameOptions.as_view(), name="paybyname_options"),
    path('get_current_rate/', coin_views.GetCurrentRate.as_view(), name="getcurrentrate"),



]

web/exmr/apps/common/urls.py
from django.urls import path
from django.views.generic import TemplateView

from apps.common.views import CoinRequestView, HelpTemplateView, HelpView, Update,\
                              PluginDownloadView, StaticPageView, ApiView, ApiTemplateView, ModeChangeView

app_name = 'common'

urlpatterns = [
    path('coin-hosting/', CoinRequestView.as_view(),  name='coinhosting'),
    path('api/', ApiView.as_view(), name='api'),
    path('api/<slug:slug>/', ApiTemplateView.as_view(), name='apitopic'),
    path('help/', HelpView.as_view(), name='help'),
    path('help/<slug:slug>/', HelpTemplateView.as_view(), name='helptopic'),
    path('plugin-download/', PluginDownloadView.as_view(), name='plugin-download'),
    path('update/', Update.as_view(), name='update'),
    path('coming-soon/', TemplateView.as_view(template_name='common/beta.html'), name='beta'),
    path('docs/<slug>/', StaticPageView.as_view(), name='staticpage'),
    path('change_color/', ModeChangeView.as_view(), name='change_mode')
]

web/exmr/apps/merchant_tools/urls.py
from django.urls import path
from django.views.generic import TemplateView

from apps.merchant_tools.views import (ButtonMakerView, CryptoPaymment, PaymentFormSubmitView, MercDocs,
                                       URLMakerView, URLMakerInvoiceView, POSQRMakerView, POSQRPayView, POSQRCompletePaymentView,ButtonMakerPayView,
                                       HelpTemplateView, DonationButtonMakerView, SimpleButtonMakerView, ButtonMakerContinuePayment, ButtonMakerInvoice,
                                       CryptoPaymmentV2, DonationButtonMakerInvoice, CryptoPaymmentSimple, SimpleButtonMakerInvoice, MTest)
# GCPS_V2
from apps.merchant_tools.views import (POSCalcView,POSCalcCoinSelect, POSCALCPayView)

app_name = 'mtools'

urlpatterns = [
    path('buttonmaker/', ButtonMakerView.as_view(),  name='buttonmaker'),
    path('donationbuttonmaker/', DonationButtonMakerView.as_view(),  name='donationbuttonmaker'),
    path('simplebuttonmaker/', SimpleButtonMakerView.as_view(),  name='simplebuttonmaker'),
    path('urlmaker/', URLMakerView.as_view(),  name='urlmaker'),
    path('invoice/<token>/', URLMakerInvoiceView.as_view(),  name='urlmakerinvoice'),
    path('make-payment/', CryptoPaymment.as_view(),  name='cryptopay'), 
    path('payment-process-1/', PaymentFormSubmitView.as_view(),  name='payprocess'),
    path('merchant-tools-docs/', MercDocs.as_view(),  name='mercdocs'),
    path('help/<slug:slug>/', HelpTemplateView.as_view(), name='helptopic'),
    path('pos-calculator/', POSCalcView.as_view(),  name='poscalc'),
    path('pos-calculator-select/', POSCalcCoinSelect.as_view(),  name='poscalcpaysel'),
    path('pos-calculator-final/', POSCALCPayView.as_view(),  name='poscalcfinal'),
    path('pos-qr/', POSQRMakerView.as_view(),  name='posqrmaker'),
    path('pos-qr/<token>/', POSQRPayView.as_view(),  name='pospay'),
    path('POSQRCompletePayment/', POSQRCompletePaymentView.as_view(),  name='posqrpay'),
    path('update-btn-form/', ButtonMakerContinuePayment.as_view(),  name='updatebtnmaker'),
    path('button-payment/', CryptoPaymmentV2.as_view(),  name='cryptopayV2'),
    path('simple-button-payment/', CryptoPaymmentSimple.as_view(),  name='cryptopaysimple'),
    path('donation-button-invoice-generate/', DonationButtonMakerInvoice.as_view(),  name='donorbtnpay'),
    path('simple-button-invoice-generate/', SimpleButtonMakerInvoice.as_view(),  name='simplebtnpay'),
    path('button-invoice-generate/', ButtonMakerInvoice.as_view(),  name='btnpay'),
    path('button-invoice-generate/<token>/', ButtonMakerInvoice.as_view(),  name='btnpay2'),
    path('simple-invoice-generate/<token>/', SimpleButtonMakerInvoice.as_view(),  name='simplebtnpay2'),
    path('donation-button-invoice-generate/<token>/', DonationButtonMakerInvoice.as_view(),  name='donorbtnpay2'),
    path('button-invoice-payment/', ButtonMakerPayView.as_view(),  name='btnqrcode'),
    path('mtest/', MTest.as_view(),  name='mtest'),
]

web/exmr/exmr/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from apps.coins.views import PublicCoinVote
from django.conf.urls import handler404, handler500
from apps.common.views import HomeView, ContactView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('s9tjjy6e8w6paimpmoxa4sfa651n6j.html/', TemplateView.as_view(template_name='s9tjjy6e8w6paimpmoxa4sfa651n6j.html'), name="facebook html"),
    path("zohoverify/verifyforzoho.html", TemplateView.as_view(template_name="verifyforzoho.html"), name="zoho"),
    path('', HomeView.as_view(), name='home'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('password-reset-done', PasswordResetDoneView.as_view(template_name='accounts/forgot_password_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('', include('apps.accounts.urls')),
    path('coins/', include('apps.coins.urls')),
    path('store/', include('apps.store.urls')),
    path('common/', include('apps.common.urls')),
    path('merchant_tools/', include('apps.merchant_tools.urls'), name='merchant_tools'),
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(template_name="accounts/login.html"), name='signin'),
    path('sign-up/', TemplateView.as_view(template_name='accounts/signup.html'),
         name='signup'),
    path('merchant-tools/', TemplateView.as_view(template_name='common/merchant-tools.html'), name='merchant-tools'),
    path('public-coin-votes/', PublicCoinVote.as_view(), name='public coin vote'),
    path('forgot-password/', TemplateView.as_view(template_name='accounts/forgot-password.html'),
         name='forgot-password'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('select2/', include('django_select2.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/exmr/apps/common/models.py
from ckeditor.fields import RichTextField, RichTextFormField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

AUTH_TYPE = (
    ('HTTP Auth', _('HTTP Auth')),
    ('HMAC', _('HMAC')),
    ('N/A', _('N/A')),
)

class Currency(models.Model):
    """
    Model to save different currencies
    """
    name = models.CharField(_('name'), max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Currency')
        verbose_name_plural = _('Currencies')


class SocialLink(models.Model):
    """
    Model to save different social media link
    """
    provider = models.CharField(_('provider'), max_length=255)
    link = models.URLField(_('link'))
    publish = models.BooleanField(default=True)

    class Meta:
        verbose_name = _('Social Link')
        verbose_name_plural = _('Social Links')

    def __str__(self):
        return self.provider


class CoinRequest(models.Model):
    """
    Model to save incoming request for coins
    """
    requester_name = models.CharField(max_length=64)
    requester_email = models.EmailField()
    coin_symbol = models.CharField(max_length=10)
    coin_name = models.CharField(max_length=64)
    coin_url = models.CharField(max_length=128)
    coin_algorithm = models.CharField(max_length=255)
    coin_source_url = models.CharField(max_length=128)
    
    def __str__(self):
        return self.coin_name

class FAQ(models.Model):
    """
    Model to save frequently asked questions
    """
    faq_question = models.CharField(max_length=512)
    faq_answer = models.TextField()

    def __str__(self):
        return self.faq_question


class HelpSidebar(models.Model):
    """
    Model to save help sidebar topics and their answers
    """
    help_topic = models.CharField(max_length=64)
    help_answer = RichTextUploadingField()
    order_index = models.IntegerField()
    slug = models.SlugField(default=slugify(help_topic))

    def __str__(self):
        return self.help_topic

    def save(self, *args, **kwargs):
        self.slug = slugify(self.help_topic)
        super(HelpSidebar, self).save(*args, **kwargs)


class LegalSidebar(models.Model):
    """
    Model to save help sidebar topics and their answers
    """
    help_topic = models.CharField(max_length=64)
    help_answer = RichTextUploadingField()
    order_index = models.IntegerField()
    slug = models.SlugField(default=slugify(help_topic))

    def __str__(self):
        return self.help_topic

    def save(self, *args, **kwargs):
        self.slug = slugify(self.help_topic)
        super(LegalSidebar, self).save(*args, **kwargs)


class PluginDownload(models.Model):
    """
    Model to Save details in merchant tools plugins option
    """
    shopping_cart_logo = models.ImageField(_('image'))
    last_update = models.DateField(auto_now_add=True)
    download_url = models.URLField(_('link'))
    auth_type = models.CharField(max_length=10)
    zero_confirm = models.BooleanField(blank=True)
    video_url = models.URLField(_('Video URL'))


class StaticPage(models.Model):
    page_name = models.CharField(max_length=128, unique=True)
    topic = models.CharField(max_length=128)
    content = RichTextUploadingField()
    slug = models.SlugField(default=slugify(page_name))

    def __str__(self):
        return self.page_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.page_name)
        super(StaticPage, self).save(*args, **kwargs)

class ContactUs(models.Model):
    name = models.CharField(null=False, max_length=100)
    email = models.EmailField(null=False)
    category = models.CharField(max_length=30, null=True)
    message = models.TextField()
    
    def __str__(self):
        return self.name



class API(models.Model):
    """
    Model to save frequently asked questions
    """
    api_question = models.CharField(max_length=512)
    api_answer = models.TextField()

    def __str__(self):
        return self.api_question


class InformationalSidebar(models.Model):
    """
    Model to save help sidebar topics and their answers
    """
    inform_topic = models.CharField(max_length=64)
    inform_answer = RichTextUploadingField()
    order_index = models.IntegerField()
    slug = models.SlugField(default=slugify(inform_topic))

    def __str__(self):
        return self.inform_topic

    def save(self, *args, **kwargs):
        self.slug = slugify(self.inform_topic)
        super(InformationalSidebar, self).save(*args, **kwargs)


class ReceivingSidebar(models.Model):
    """
    Model to save help sidebar topics and their answers
    """
    receive_topic = models.CharField(max_length=64)
    receive_answer = RichTextUploadingField()
    order_index = models.IntegerField()
    slug = models.SlugField(default=slugify(receive_topic))

    def __str__(self):
        return self.receive_topic

    def save(self, *args, **kwargs):
        self.slug = slugify(self.receive_topic)
        super(ReceivingSidebar, self).save(*args, **kwargs)

class AnnouncementHome(models.Model):

    title = models.CharField(max_length=128)
    description = models.CharField(max_length=2048)
    visit = models.CharField(max_length=128)
    link = models.URLField()

    def __str__(self):
        return self.visit

class UITheme(models.Model):
    theme_name = models.CharField(max_length=128)
    file_name = models.CharField(max_length=128)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.theme_name

web/exmr/apps/common/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _

from .models import CoinRequest, ContactUs

class CoinRequestForm(ModelForm):
    
    """
    Form for updating Mobile Number.

    """
    class Meta:
        model = CoinRequest
        fields = '__all__'

class ContactForm(ModelForm):
	"""
	Form for contact us
	"""

	class Meta:
		model = ContactUs
		fields = '__all__'

web/exmr/templates/common/contact.html
{% extends 'gcps/testbase.html' %} {% load staticfiles %} {% load i18n %} {% block content %}
<section class="section section-pad">
    <div class="bx-ash ">
    <div class="dark-page-header text-white text-center">
        <h1>Support</h1>
        <h4>Need a little help?</h4>
    </div>
</div>
<div class="account-setting-wrap">
    <div class="container">
        <div class="page-row" style="height: 25px;"></div>
        <div class="page-row page-row-expanded">
            <div class="container">
            <style>
                p { padding:0px; margin:0px; }
            </style>
                <div class="panel panel-default">
                <div class="panel-heading"><h4>Contact Us</h4></div>
                <div class="panel-body">
              
                        <h6>This form is not for support requests! All support requests must be via the <a href="{% url 'common:help' %}">Support Ticket</a> system. Any support requests sent via this form will be ignored.</h6>
                        <h6>If you want to add your coin to GetCryptoPayments, <a href="{% url 'coins:add-public-coin' %}">click here</a>.</h6>
                        
                        <form action="." method="POST">
                            {% csrf_token %}
                            <table class="table table-bordered table-condensed" style="border: none">
                                <thead>
                                    <tr style="border: none"><th class="center" style="border: none" colspan="3"><h3>Submit Message</h3></th></tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td style="border: none"><span class="text-white font-large">Your Name</span></td>
                                        <td style="border: none"><input type="text" id="id_name" class="form-control" name="name" value="" required=""></td>
                                    </tr>
                                    <tr>
                                        <td style="border: none"><span class="text-white font-large">Your Email</span></td>
                                        <td style="border: none"><input type="email" id="id_email" class="form-control" name="email" value="" required=""></td>
                                    </tr>
                                    <tr>
                                        <td style="border: none"><span class="text-white font-large">Category</span></td>
                                        <td style="border: none"><select id="id_category" class="form-control" name="category" required=""><option value="Sales">Sales</option><option value="ICO Services">ICO Services</option><option value="Partnership Requests">Partnership Requests</option><option value="Other">Other</option></select></td>
                                    </tr>
                                    <tr>
                                        <td style="border: none"><span class="text-white font-large">Message</span></td>
                                        <td style="border: none"><textarea name="message" id="id_message" class="form-control" rows="10" required=""></textarea></td>
                                    </tr>
                                    
                                    <tr>
                                        <td style="border: none" colspan="2" class="text-center"><button class="btn btn-outline-orange">Submit Message</button></td>
                                    </tr>
                                </tbody>
                            </table>
                            <input type="hidden" name="screen_res" value="1366x768">
                        </form>           
                    </div>
                </div>
            </div>   


</div>
        </div>
    </div>
</section>

{% endblock %} {% block script %}
<script>
    grecaptcha.ready(function () {
        grecaptcha.execute('6LfNl2cUAAAAAKoPIBFAyyN9tF9hgCKBIrX2n_bo', {
                action: 'action_name'
            })
            .then(function (token) {
                captchaResult = true;
            });
    });
</script>
{% endblock %}

web/exmr/templates/common/inform-template.html
{% extends 'gcps/testbase.html' %} {% load staticfiles %} {% block content %} {% load i18n %}
<section class="section section-pad" style="padding-bottom: 1em">
    <div class="container">
        <div class="bx-ash mb-2">
            <div class="grid-2-bx" style="display: inline">
                <ul class="row nav nav-pills nav-fill " >
                    <li class="col-md-4 col-xs-4 col-lg-2 col-sm-6 col-xl-2 nav-item justify-content-center" >
                        <a href="{% url 'accounts:profile' %}" class="v-mid dashboard-nav" >
                            
                            <span class="dashboard-span hidden-xs hidden-sm wallet-menu"><i class="fas fa-tachometer-alt fa-2x  mr-4"></i>{% trans '&nbsp;&nbsp;&nbsp;Home' %}</span>
                        </a>
                        <!-- <i class="fas fa-2x fa-wallet"></i>
                        <a class="nav-link" href="{% url 'accounts:profile' %}"></a> -->
                    </li>
                    <li class="col-md-4 col-xs-12 col-lg-2 col-sm-6 col-xl-2 nav-item justify-content-center" >
                            <a href="{% url 'coins:wallets' %}" class="v-mid dashboard-nav" >
                                <span class="dashboard-span hidden-xs hidden-sm wallet-menu" style="">
                                    <i class="fas fa-2x fa-wallet mr-2"></i>{% trans 'Your Wallet' %}
                                </span>
                            </a>
                        <!-- <a class="nav-link" href="{% url 'coins:wallets' %}">{% trans 'Your Wallet' %}</a> -->
                    </li>
                    <li class=" col-md-4 col-xs-12 col-lg-2 col-sm-6 col-xl-2 nav-item justify-content-center" >
                            <a href="{% url 'coins:coin-settings' %}" class="v-mid dashboard-nav" >
                                
                                <span class="dashboard-span hidden-xs hidden-sm wallet-menu"><i class="fas fa-coins  fa-2x "></i>{% trans 'Coin Settings' %}</span>
                            </a>
                        <!-- <a class="nav-link" href="{% url 'coins:coin-settings' %}">{% trans 'Coin Settings' %}</a> -->
                    </li>
                    <li class=" col-md-4 col-xs-12 col-lg-2 col-sm-6 col-xl-2 nav-item justify-content-center" >
                        <a href="{% url 'coins:transaction-history' %}" class="v-mid dashboard-nav " >
                                
                                <span class="dashboard-span hidden-xs hidden-sm wallet-menu"><i class="fas fa-receipt fa-2x mr-1"></i> {% trans 'Transactions' %}</span>
                        </a>
                        <!-- <a class="nav-link" href="{% url 'coins:transaction-history' %}">{% trans 'Transactions' %}</a> -->
                    </li>
                    <li class="col-md-4 col-xs-12 col-lg-2 col-sm-6 col-xl-2 nav-item justify-content-center" >
                            <a href="{% url 'mtools:poscalc' %}" class="v-mid dashboard-nav" >
                                
                                <span class="dashboard-span hidden-xs hidden-sm wallet-menu"><i class="fas fa-shopping-cart  fa-2x mr-2"></i> {% trans 'Quick POS' %}</span>
                            </a>
                    </li>
                    <li class="col-md-4 col-xs-12 col-lg-2 col-sm-6 col-xl-2 nav-item justify-content-center" >
                            <a href="{% url 'coins:paybyname' %}" class="v-mid dashboard-nav" 
                                
                                <span class="dashboard-span hidden-xs hidden-sm wallet-menu"><i class="fas fa-user-tie  fa-2x mr-2"></i>{% trans 'PayByName' %}</span>
                            </a>
                        <!-- <a class="nav-link" href="{% url 'coins:paybyname' %}"> {% trans 'PayByName' %}</a> -->
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>
<section class="section section-pad" style="padding-top: 1em;">
    <div class="bx-ash ">
    <div class="merchant-tools merchant-one text-white coin-payment-head">
        <h1>Merchant Tools</h1>
        <h3>Getcryptopayments API </h3>
    </div>
</div>
<div class="container-fluid xs-padx1 mt-4 mb-4">
    <div class="row xs-padx1">
        <div class="col-xs-12 col-md-4 ">
            <div class="help-sidebar">
                <h3 class="sidebar-label text-white">Informational Commands</h3>
                {% for topic in inform_sidebar %}

                <li>
                    <a href="{% url 'common:apitopic' topic.slug %}" class="sidebar-link">{{topic.inform_topic}}</a>
                </li>
                {% endfor %}
                <h3 class="sidebar-label text-white">Receiving Payments</h3>
                {% for topic in receive_sidebar %}

                <li>
                    <a href="{% url 'common:apitopic' topic.slug %}" class="sidebar-link ">{{topic.receive_topic}}</a>
                </li>
                {% endfor %}
            </div>

        </div>
        <div class="col-xs-12 col-md-8 text-justify">
            {% if details %}
            {% for obj in details %}
            <div id="help-answer" class="text-justify text-white">
                {{obj.inform_answer|safe}}
            </div>
            {% endfor %}
            {% else %}
            {% for obj in details1 %}
            <div id="help-answer" class="text-justify text-white">
                {{obj.receive_answer|safe}}
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
</section>

<!-- <section>
    <div class="merchant-tools merchant-one">
        <h1>Merchant Tools</h1>
        <h3>Getcryptopayments API </h3>
    </div>
    <div class="container-fluid xs-padx1 mt-4 mb-4">
        <div class="col-xs-12 xs-padx1">
            <div class="col-xs-12 col-md-4 ">
                <div class="help-sidebar">
                    <h3 class="sidebar-label">Informational Commands</h3>
                    
                   
                    {% for topic in inform_sidebar %}

                    <li>
                        <a href="{% url 'common:apitopic' topic.slug %}" class="sidebar-link">{{topic.inform_topic}}</a>
                    </li>
                    {% endfor %}
                    <h3 class="sidebar-label">Receiving Payments</h3>
                    {% for topic in receive_sidebar %}

                    <li>
                        <a href="{% url 'common:apitopic' topic.slug %}" class="sidebar-link">{{topic.receive_topic}}</a>
                    </li>
                    {% endfor %}
                </div>

            </div>
            <div class="col-xs-12 col-md-8 text-justify">
                {% if details %}
                {% for obj in details %}
                <div id="help-answer" class="text-justify">
                    {{obj.inform_answer|safe}}
                </div>
                {% endfor %}
                {% else %}
                {% for obj in details1 %}
                <div id="help-answer" class="text-justify">
                    {{obj.receive_answer|safe}}
                </div>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</section> -->

{% block script %}
<script src="{% static 'js/exmr.js' %}"></script>
{% endblock %}
{% endblock %}

web/exmr/templates/common/message.html
{% extends 'gcps/testbase.html' %}

{% block content %}
    {% load i18n %}
     {% for message in messages %}
     <section class="section section-pad" style="padding-bottom: 1em">
            <div class="container">
                <div class="bx-ash mb-2">
                    <div class="min-height-content" style="color: white"><h2>{{ message }}</h2>
                    </div> 
                </div>
            </div>
        </section>
	    
   {% endfor %}
{% endblock %}