web/exmr/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.views.generic import TemplateView

from apps.accounts import views
from apps.accounts.forms import CustomPasswordResetForm
from apps.accounts.views import FeedbackListView

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.DashboardView.as_view(), name='profile'),
    path('address/', views.AddressView.as_view(), name='address'),
    path('add-new-address-complete/', views.AddAddressCompleteView.as_view(), name='add_new_address_complete'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('settings/', views.AccountSettings.as_view(), name='settings'),
    path('save-public-info/', views.PublicInfoSave.as_view(), name='save_public_info'),
    path('save-security-info/', views.SecurityInfoSave.as_view(), name='save_security_info'),
    path('save-ipn-settings/', views.IPNSettingsSave.as_view(), name='save_ipn_settings'),
    path('sign-up/', views.SignUpView.as_view(), name='signup'),
    path('ref-signup/<slug:mid>/', views.SignUpView.as_view(), name='signup'),
    path('sign-up-complete/', views.SignUpCompleteView.as_view(), name='signup_complete'),
    path('activate/<slug:key>', views.ProfileActivationView.as_view(), name='registration_activate'),
    path('password-reset/', PasswordResetView.as_view(template_name='accounts/forgot_password.html',
                                                     form_class=CustomPasswordResetForm), name='reset_password'),

    path('2fa-accounts/', views.TwoFactorAccountView.as_view(), name='accounts_2fa'),
    # path('2fa-list/', views.TwoFactorAccountList.as_view(), name='2fa_list'),
    path('delete-2fa/<int:pk>/', views.DeleteTwoFactorAccount.as_view(), name='delete_2fa'),
    path('delete-address/<int:pk>/', views.DeleteAddress.as_view(), name='delete_address'),
    path('verify-2fa/', views.Verify2FAView.as_view(), name='verify_2fa'),
    path('feedback/<slug:slug>/', FeedbackListView.as_view(), name='feedback'),
    path('feedback/', FeedbackListView.as_view(), name='feedbac'),
    path('verify-login/', views.VerifyLoginView.as_view(), name='verify_login'),
    path('login-notice/', views.LoginNoticeView.as_view(), name='login_notice'),
    path('kyc/', views.KYCView.as_view(), name='kyc'),
    path('kyc-accept/', views.KYCAcceptanceView.as_view(), name="kyc_accept"),
    path('view-profile-paybyname/', views.PayByNameCheck.as_view(), name="paybyname_check"),
]

web/exmr/apps/coins/urls.py
from django.urls import path
from django.views.generic import TemplateView

from apps.coins import views as coin_views
from apps.accounts.forms import CustomPasswordResetForm

app_name = 'coins'

urlpatterns = [
    path('wallets/', coin_views.WalletsView.as_view(), name='wallets'),
    path('supported/<str:type>/', coin_views.SupportedCoinView.as_view(),
         name='supported_coins'),
    path('newaddr/<str:currency>/', coin_views.NewCoinAddr.as_view(), name='newaddr'),
    path('<str:currency>/address/<int:pk>/update/', coin_views.CoinAddrUpdate.as_view(), name='label'),
    path('hidden_addr/<str:currency>/', coin_views.HiddenAddress.as_view(), name='hidden_addr'),
    path('newaddr/<str:currency>/hide/<int:pk>/', coin_views.CoinHide.as_view(), name='hide'),
    path('coin-conversion/<str:from>/<str:to>/',
         coin_views.ConvertCoinsView.as_view(), name='coin_conversion'),
    path('coin-conversion-confirm/',
         coin_views.CoinConversionFinalView.as_view(), name='conversion_final'),
    path('checkout/', TemplateView.as_view(template_name='coins/coin-checkout.html')),
    path('add-coin/', coin_views.AddNewCoin.as_view(), name='add-coin'),
    path('coin-settings/',coin_views.CoinSettings.as_view(),name='coin-settings'),
    path('coin-settings/setup/',coin_views.SettingSetUp.as_view(),name='setting-setup'),
    path('coin-settings/omini/',coin_views.OMiniView.as_view(),name='omini-coin'),
    path('coin-settings/ripple/',coin_views.RippleView.as_view(),name='ripple'),
    path('coin-withdrawal/<str:code>/', coin_views.CoinWithdrawal.as_view(), name='coin-withdrawal'),
    path('send/<slug:slug>/', coin_views.SendView.as_view(), name='send'),
    path('send-success/', coin_views.SendSuccessView.as_view(), name='send-success'),
    path('sendconfirm/<slug:slug>/', coin_views.SendConfirmView.as_view(), name='sendconfirm'),
    path('vote-details/<str:currency>/', coin_views.VoteDetailsView.as_view(), name='vote-details'),
    path('refund-claim/<slug:slug>/', coin_views.RefundClaimView.as_view(), name='refund-claim'),
    path('add-public-coin/', coin_views.NewCoinAddView.as_view(), name='add-public-coin' ),
    path('paybyname/', coin_views.PayByNameView.as_view(), name='paybyname' ),
    path('paybyname-payment/<int:pk>/', coin_views.PayByNamePayView.as_view(), name='paybyname-payment' ),
    path('paybyname-payment-final/', coin_views.PayByNamePaymentView.as_view(), name='pbnfinal' ),
    path('copromotion-form/', coin_views.CopromotionView.as_view(), name="copromotion-form"),
    path('get_balance/', coin_views.BalanceView.as_view(), name="get_balance"),
    path('get_all_coin_balance/', coin_views.AdminBalanceView.as_view(), name="get_all_coin_balance"),
    path('coin-vote-winners/', coin_views.VoteWinners.as_view(), name="winners"),
    path('coin-convert/<str:currency>', coin_views.CoinConvertView.as_view(), name="convert_select"),
    path('coin-convert-confirmation/', coin_views.CoinConvertView2.as_view(), name="convert_select_confirm"),
    path('coin-convert-complete/', coin_views.CoinConvertView3.as_view(), name="convert_select_finish"),
    path('currency-convert/', coin_views.ConversionView.as_view(), name="currency_convert"),
    path('insufficient/', TemplateView.as_view(template_name='coins/no-money.html'), name="low-balance"),
    path('paypal-verify/', coin_views.PayPalVerifyView.as_view(), name="paypal_verify"),
    path('buy-coin/<str:currency>/',coin_views.BuyCryptoView.as_view(), name="buy_coin"),
    path('displaysupportedcoins/',coin_views.DisplaySupportedCoins.as_view(), name="displaysupportedcoins"),
    path('admin-wallet/', coin_views.AdminWallet.as_view(), name="admin_wallet"),
    path('admin-wallet-coins/', coin_views.AdminWalletCoin.as_view(), name="admin_wallet_coin"),
    path('admin-coins-wallet/<str:coin>/', coin_views.AdminCoinWalletView.as_view(), name="admin_coin_wallet"),
    path('user-wallet/<int:pk>/', coin_views.UserWallet.as_view(), name="user_wallet"),
    path('transaction-history/', coin_views.TransactionHistoryView.as_view(), name='transaction-history'),
    path('transaction-history/<str:type>/', coin_views.TransactionDetails.as_view(), name='transaction-history-details'),
    path('download-txn/', coin_views.DownloadTxnView.as_view(), name="download_txn"),
    path('paybyname-submit', coin_views.PayByNameSubmit.as_view(), name="paybyname_submit"),
    path('paybyname-options/<int:pk>/', coin_views.PayByNameOptions.as_view(), name="paybyname_options"),
    path('get_current_rate/', coin_views.GetCurrentRate.as_view(), name="getcurrentrate"),



]

web/exmr/exmr/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from apps.coins.views import PublicCoinVote
from django.conf.urls import handler404, handler500
from apps.common.views import HomeView, ContactView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('s9tjjy6e8w6paimpmoxa4sfa651n6j.html/', TemplateView.as_view(template_name='s9tjjy6e8w6paimpmoxa4sfa651n6j.html'), name="facebook html"),
    path("zohoverify/verifyforzoho.html", TemplateView.as_view(template_name="verifyforzoho.html"), name="zoho"),
    path('', HomeView.as_view(), name='home'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('password-reset-done', PasswordResetDoneView.as_view(template_name='accounts/forgot_password_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('', include('apps.accounts.urls')),
    path('coins/', include('apps.coins.urls')),
    path('store/', include('apps.store.urls')),
    path('common/', include('apps.common.urls')),
    path('merchant_tools/', include('apps.merchant_tools.urls'), name='merchant_tools'),
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(template_name="accounts/login.html"), name='signin'),
    path('sign-up/', TemplateView.as_view(template_name='accounts/signup.html'),
         name='signup'),
    path('merchant-tools/', TemplateView.as_view(template_name='common/merchant-tools.html'), name='merchant-tools'),
    path('public-coin-votes/', PublicCoinVote.as_view(), name='public coin vote'),
    path('forgot-password/', TemplateView.as_view(template_name='accounts/forgot-password.html'),
         name='forgot-password'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('select2/', include('django_select2.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/exmr/apps/coins/forms.py
from django import forms

from apps.coins.models import CoinConvertRequest, NewCoin


class ConvertRequestForm(forms.ModelForm):
    """
    Form used to save the coin requests
    """
    wallet_from = forms.CharField()
    wallet_to = forms.CharField()

    class Meta:
        model = CoinConvertRequest
        fields = ('wallet_from', 'wallet_to')


class NewCoinForm(forms.ModelForm):

	class Meta:
		model = NewCoin
		exclude = ['']

web/exmr/templates/coins/coin_refund_claim.html
{% extends 'accounts/dashboard-base.html' %}
{% load staticfiles %}
{% block content %}
{% load transaction_status %}
{% load i18n widget_tweaks %}

<div class="withdrawal">
  <div class="container">
    {%for msg in msgs%}
      <div class="alert {{msg.class}}">
          <strong>{{msg.text}}</strong> 
        </div>
      {%endfor%}
      <div class="alert alert-success hidden">
          <strong>Claim Process initiated. Rdirecting to Home Page</strong> 
        </div>
        {%if not msgs%}
                <div class="panel panel-default">
                  <div class="panel-heading"><b>{% trans 'Claim  Refund' %}</b></div>
                  <div class="panel-body">
                    <div class="row">
                      <div class="col-sm-4 lh40" align="right">
                        <p><b>{% trans 'Payment ID' %} :</b></p>
                        <p><b>{% trans 'Refund Amount' %} :</b</p>
                        <p><b>{% trans 'Send Refund To' %} : </b</p>
                      </div>
                      <div class="col-sm-6 lh40" >
                        <p> {{transaction_obj.system_tx_id}}</p>
                        <div class="row m0 mb20">
                          {%csrf_token%}
                        <p>{{transaction_obj.amount}} {{ transaction_obj.currency }}</p>
                        <input type="text" class="form-control form-groupwallet-send-coin-addr" id="send_addr"/>
                        <p class="error hidden" id="send_error" style="margin-bottom:-25px">* required</p><br>
                        <button class="btn btn-primary" id="claim_refund"> {% trans 'Claim Refund' %} </button>
                        <img id="loading-image" src="{% static 'images/load.gif' %}" style="display:none;height: 60px;"/>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
      {%endif%}
</div>
{% endblock %}

{% block script %} 
<script>
              $('#claim_refund').click(function(){

              var send_addr = $('#send_addr').val().trim()
              var is_valid = true;
              if (send_addr.length==0)
              {
              $('#send_error').removeClass('hidden');
              is_valid = false;
              }
              if(is_valid){
                data = {};
                data['transation_id'] = "{{transaction_obj.system_tx_id}}";
                data['send_addr'] = send_addr;
                data['csrfmiddlewaretoken'] = "{{csrf_token}}";
                
                $.post(window.location.href, data, function(result){
                  $('.alert-success').removeClass('hidden')
                  $('.withdrawal .panel-default').addClass('hidden')
                  setTimeout(function(){ 
                    window.location.href= "{% url 'coins:wallets' %}"
                   }, 2000);
    
              });
              }

              })
              $('#send_addr').keyup(function(){

                var send_addr = $('#send_addr').val().trim()
                if (send_addr.length==0)
                {
                  $('#send_error').removeClass('hidden');
                }
                else{
                    if(!$('#send_error').hasClass('hidden'))
                    {
                      $('#send_error').addClass('hidden');
                    }
                }


              })
</script>
{% endblock %}

web/exmr/templates/coins/create_normal.html
{% extends 'accounts/dashboard-base.html' %} {% load staticfiles widget_tweaks i18n %}
<div></div>
{% load transaction_status %} {% block dashboard_heading %}
<div class="dashboard-bg">
    <div class="merchant-tools merchant-one coin-payment-head">
        <div class=" container merchant-box">COIN SETTINGS
        </div>
    </div>
</div>
{% endblock %} {% block dashboard_wrapper_content %}

<div class="dashboard-wrapper">
    <div class="dasboard-head ">
        <div class="panel panel-default">
            <div class=" dasboard-head pad10">
                <ul class="nav nav-pills">
                    <li class="active">
                        <a href="{% url 'coins:setting-setup' %}">Setup Wizard</a>
                    </li>
                    <li>
                        <a href="{% url 'coins:coin-settings' %}">Std.coin</a>
                    </li>
                    <li>
                        <a href="{% url 'coins:omini-coin' %}">Omini coin</a>
                    </li>
                    <li>
                        <a href="{% url 'coins:ripple' %}">Ripple</a>
                    </li>
                    <li>
                        <a href="#">Escrow</a>
                    </li>
                    <li>
                        <a href="#">Paypal/other</a>
                    </li>
                    <li>
                        <a href="#"></a>
                    </li>
                </ul>
            </div>
            <div class="panel-body" style="text-align: center;">
                <div class="accept-table-wrap">
                    <table class="table table-border table-responsive-md">
                        <thead>
                            <tr>
                                <th>Enabled</th>
                                <th>Coin</th>
                                <th>Your payment Address
                                    <h6>(only needed for ASAP modes)</h6>
                                </th>
                                <th>Payout Mode </th>
                                <th>Discount</th>
                                <th>Maximum value per Transaction</th>
                            </tr>
                        </thead>
                        <div class="form-group">
                        <form  method="POST" action="">
                                    {% csrf_token %}
                                {{ formset.management_form }}
                        
                        {% for form in formset %}
                        
                        <tbody>
                        <tr>
                                <td>
                        
                                    {{form.enabled}}
                                </td>
                                <td>
                                    {{form.coin}}
                                        
                                </td>
                                <td>
                                   {{form.payment_address}}
                                </td>
                                <td>
                                    {{form.payment_mode}}
                                </td>
                                <td>
                                    {{form.discount_percentage}}
                                </td>
                                <td>                                 
                                    {{form.maximum_per_transaction}}                                        
                                </td>
                            </tr>
                        {% endfor %}
                                
                        </tbody>
                       
                    </table> 
                    <button class="btn btn-primary" type="submit" >Create</button>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

web/exmr/templates/coins/omini.html
{% extends 'accounts/dashboard-base.html' %} {% load staticfiles widget_tweaks i18n %}
<div></div>
{% load transaction_status %} {% block dashboard_heading %}<h4 class="text-theme b-4 dashboard">COIN SETTINGS</h4>
{% endblock %} {% block dashboard_wrapper_content %}
<section class="section section-pad" style="padding-bottom: 1em; padding-top: 1em">
    <div class="container">
        <div class="bx-ash mb-2">
            <div style="padding-bottom: 10px;">
                <ul class="nav nav-pills">
                    <li class="nav-item">
                      <a class="nav-link active dashboard-nav" href="{% url 'coins:setting-setup' %}">Setup Wizard</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link dashboard-nav" href="{% url 'coins:coin-settings' %}">Std.coin</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link dashboard-nav" href="{% url 'coins:omini-coin' %}">Omini coin</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link dashboard-nav" href="{% url 'coins:ripple' %}" tabindex="-1" aria-disabled="true">Ripple</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link dashboard-nav" href="#" tabindex="-1" aria-disabled="true">Escrow</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link dashboard-nav" href="#" tabindex="-1" aria-disabled="true">Paypal/other</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link dashboard-nav" href="#" tabindex="-1" aria-disabled="true"></a>
                      </li>
                  </ul>
            </div>
            <div class="panel-body" style="text-align: center;">
                <div class="accept-table-wrap">
                    <table class="table table-border table-responsive-md text-white">
                        <thead>
                            <tr style="border: none">
                                <th>Enabled</th>
                                <th>Coin</th>
                                <th>Your payment Address
                                    <br>(only needed for ASAP modes)
                                </th>
                                <th>Payout Mode </th>
                                <th>Discount</th>
                                <th>Maximum value per Transaction</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr style="border: none">
                                <td class="table-style" colspan="6">{% trans 'No Omini coins to be displayed ' %}</td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
                <div class="col text-center">
                <button type="submit" class="btn btn-success text-center" >Select</button>
                </div>             
                </form> 
                </body>
            </div>
                
        </div>
    </div>
</section>


{% endblock %}

web/exmr/templates/coins/system_coin_stat.html
{% extends 'gcps/testbase.html' %} {% load static %}{% load transaction_status %}{% block style %}
<link rel="stylesheet" type="text/css"
    href="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.16/b-1.5.1/b-html5-1.5.1/b-print-1.5.1/r-2.2.1/sc-1.4.4/datatables.min.css" />
{% endblock %} {% block content %}

<section class="section section-pad">
    <div class="col-12 text-center my-3 py-3">
        <div id="canvas-holder" class="col-12 col-md-6 offset-md-3">
            <canvas id="chart-area"></canvas>
        </div>
    </div>
    <div class=" bx-ash col-12 p-md-5 pb-5 pt-5">
        <table id="data_table" class="table table-border table-responsive-md" style="width:100%; ">
            <thead>
                <tr style="border: none">
                    <th scope="col">#</th>
                    <th scope="col">Coin Name</th>
                    <th scope="col">Coin Code</th>
                    <th scope="col">Balance</th>
                    <th scope="col">USD</th>
                </tr>
            </thead>
            <tbody>
                {% for key,tempcoin in coins.items %}

                <tr style="border: none">
                    <th scope="row" style="border-top: none;">{{forloop.counter}}</th>
                    <td><a href="{% url 'coins:admin_coin_wallet' coin=tempcoin.coin_code %}"><img src="{{tempcoin.image}}" class="img-fluid w60px">{{tempcoin.coin_name}}</a></td>
                    <td>{{tempcoin.coin_code}}</td>
                    <td id="bal_{{tempcoin.coin_code}}">
                        <img id="loading-image_{{coin_code}}" src="{% static 'images/load.gif' %}"
                            style="display:none;height: 20px;" />
                    </td>
                    <td id="val_{{tempcoin.coin_code}}">
                        <img id="usd-loading-image_{{coin_code}}" src="{% static 'images/load.gif' %}"
                            style="display:none;height: 20px;" />
                    </td>

                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock content %}
{% block script %}
<script src="{% static 'js/chart.min.js' %}"></script>
<script>
    function getRandomColor() {
        var letters = '0123456789ABCDEF';
        var color = '#';
        for (var i = 0; i < 6; i++) {
            color += letters[Math.floor(Math.random() * 16)];
        }
        return color;
    }
    Chart.pluginService.register({
        beforeDraw: function (chart) {
            if (chart.config.options.elements.center) {
                //Get ctx from string
                var ctx = chart.chart.ctx;

                //Get options from the center object in options
                var centerConfig = chart.config.options.elements.center;
                var fontStyle = centerConfig.fontStyle || 'Arial';
                var txt = centerConfig.text;
                var color = centerConfig.color || '#000';
                var sidePadding = centerConfig.sidePadding || 20;
                var sidePaddingCalculated = (sidePadding / 100) * (chart.innerRadius * 2)
                //Start with a base font of 30px
                ctx.font = "30px " + fontStyle;

                //Get the width of the string and also the width of the element minus 10 to give it 5px side padding
                var stringWidth = ctx.measureText(txt).width;
                var elementWidth = (chart.innerRadius * 2) - sidePaddingCalculated;

                // Find out how much the font can grow in width.
                var widthRatio = elementWidth / stringWidth;
                var newFontSize = Math.floor(30 * widthRatio);
                var elementHeight = (chart.innerRadius * 2);

                // Pick a new font size so it will not be larger than the height of label.
                var fontSizeToUse = Math.min(newFontSize, elementHeight);

                //Set font settings to draw it correctly.
                ctx.textAlign = 'center';
                ctx.textBaseline = 'middle';
                var centerX = ((chart.chartArea.left + chart.chartArea.right) / 2);
                var centerY = ((chart.chartArea.top + chart.chartArea.bottom) / 2);
                ctx.font = fontSizeToUse + "px " + fontStyle;
                ctx.fillStyle = color;

                //Draw text in center
                ctx.fillText(txt, centerX, centerY);
            }
        }
    });


    var config = {
        type: 'doughnut',
        data: {
            labels: [],
            datasets: [{
                data: [],
                backgroundColor: [],
                borderColor: [],

            }]
        },
        options: {
            elements: {
                center: {
                    text: '',
                    color: '#FF6384', // Default is #000000
                    fontStyle: 'Arial', // Default is Arial
                    sidePadding: 20 // Defualt is 20 (as a percentage)
                }
            }
        }
    };


    var ctx = document.getElementById("chart-area").getContext("2d");
    var myChart = new Chart(ctx, config);

    function addData(chart = myChart, label, data, sum,color) {
        chart.data.labels.push(label);
        chart.data.datasets.forEach((dataset) => {
            dataset.data.push(data);
            dataset.backgroundColor.push(color);
            dataset.borderColor.push(color);
        });
        chart.options.elements.center.text = sum + " USD";
        chart.update();
    }
</script>
<script type="text/javascript">
var temp_sum = 0;
    $(document).ready(function () {
        $('#data_table > tbody  > tr').each(function () {
            column = $(this).find('td')[2]
            $.ajax({
                type: "GET",
                url: "{% url 'coins:get_all_coin_balance' %}",
                data: {
                    'code': column.id.split('bal_')[1],
                },
                beforeSend: function () {
                    $("#loading-image_" + column.id.split('bal_')[1]).show();
                    $("#usd-loading-image_" + column.id.split('val_')[1]).show();
                },
                success: function (data) {
                    $("#bal_" + data['code']).text(data['balance'])
                    $("#val_" + data['code']).text(data['value'])
                    $(".val_" + data['code']).text(data['value'])
                    $("#loading-image_" + data['code']).hide();
                    $("#usd-loading-image_" + data['code']).hide();
                    temp_sum = temp_sum + parseFloat(data['value']);
                    temp_sum = parseFloat(temp_sum.toFixed(2));
                    addData(myChart, label = data['code'], data = data['value'], sum = temp_sum,color = getRandomColor());
                    // $(column).text(data);

                }
            })
        });
    });
</script>



{% endblock script %}

web/exmr/templates/coins/system_wallet_stat.html
{% extends 'gcps/base.html' %} {% load static %}{% load transaction_status %}{% block style %}
<link rel="stylesheet" type="text/css"
    href="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.16/b-1.5.1/b-html5-1.5.1/b-print-1.5.1/r-2.2.1/sc-1.4.4/datatables.min.css" />
{% endblock %} {% block content %}
<section class="section section-pad">
    <div class="col-12 pb-5 pt-5">

        <div class="col-12 d-flex justify-content-center" style="position: relative">
            <div style="position: absolute;top: 50%;max-width:100px; max-height:50px;text-overflow: ellipsis;">
                <a href="{% url 'coins:admin_wallet_coin' %}">View Coins</a>
            </div>
        </div>
    </div>
</section>
<section class="section section-pad">
    <div class=" bx-ash col-12 p-md-5 pb-5 pt-5">
        <table id="data_table" class="table table-border table-responsive-md" style="width:100%; ">
            <thead>
                <tr style="border: none">
                    <th scope="col">#</th>
                    <th scope="col">ID</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Username</th>
                    <th scope="col">Email</th>
                    <th scope="col">Balance</th>
                </tr>
            </thead>
            <tbody>
                {% for wall in wallets %}
                <tr style="border: none">
                    <td scope="row" style="border-top: none;">{{forloop.counter}}</td>
                    <td scope="col" id="id_{{wall.user.pk}}">{{wall.user.pk}}</td>
                    <td><a href="{% url 'coins:user_wallet' wall.user.pk %}">{{wall.user.first_name}}</a></td>
                    <td>{{wall.user}}</td>
                    <td> <a href="{% url 'coins:user_wallet' wall.user.pk %}">
                    {{wall.user.email}}</a></td>
                    <!-- <td id="bal_{{wall.name.code}}">
                        <img id="loading-image_{{wall.name.code}}" src="{% static 'images/load.gif' %}"
                            style="display:none;height: 20px;" />
                    </td> -->
                    <td>{% get_pk_bal_coin wall.name.code wall.user.pk %}</td>

                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock content %}
{% block script %}
{% if not all_users %}
<!-- <script type="text/javascript">
    $(document).ready(function () {
        $('#data_table > tbody  > tr').each(function () {
            column = $(this).find('td')[5];
            pk= parseInt(($(this).find('td')[1]).innerHTML);

            $.ajax({
                type: "GET",
                url: "{% url 'coins:get_balance' %}",
                data: {
                    'code': column.id.split('bal_')[1],
                    'user_id': pk,
                },
                beforeSend: function () {
                    $("#loading-image_" + column.id.split('bal_')[1]).show();
                },
                success: function (data) {
                    $("#bal_" + data['code']).text(data['balance']);
                    $("#loading-image_" + data['code']).hide();
                    // $(column).text(data);

                }
            })
        });
    });
</script> -->
{% endif %}
{% endblock script %}